spring.application.name=MathClass

# Active local profile
spring.profiles.active=local

#PostgreSQL configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JPA and Hibernate properties
spring.jpa.hibernate.ddl-auto=update

# SMTP Email
spring.mail.host=smtp.gmail.com
